/**
 * Build command tests — SDK-First Squad Mode (Phase 1)
 *
 * Tests the `squad build` pipeline which reads a squad SDK config
 * and generates .squad/ markdown files: team.md, routing.md,
 * agents/{name}/charter.md, ceremonies.md.
 *
 * Tests validate:
 *   - Generated file contents match config
 *   - Generated files include `<!-- generated by squad build -->` header
 *   - Protected files (decisions.md, history.md, orchestration-log/) are NEVER touched
 *   - --check mode exits 0 when files match, 1 when drift detected
 *   - --dry-run mode prints diff without writing
 *
 * ⚠️ Build command expected at: packages/squad-cli/src/cli/commands/build.ts
 * When Agent1's implementation lands, replace local stubs with real imports.
 *
 * @see packages/squad-sdk/src/builders/types.ts
 * @module test/build-command
 */

import { describe, it, expect, afterEach } from 'vitest';
import {
  mkdtempSync,
  writeFileSync,
  readFileSync,
  mkdirSync,
  rmSync,
  existsSync,
  readdirSync,
  statSync,
} from 'node:fs';
import { join } from 'node:path';
import { tmpdir } from 'node:os';

import type {
  TeamDefinition,
  AgentDefinition,
  ModelPreference,
  BuilderModelId,
  RoutingDefinition,
  CeremonyDefinition,
  HooksDefinition,
  SquadSDKConfig,
} from '../packages/squad-sdk/src/builders/types.js';

// ============================================================================
// Constants
// ============================================================================

const GENERATED_HEADER = '<!-- generated by squad build -->';

// ============================================================================
// Helpers
// ============================================================================

const tmpDirs: string[] = [];

function makeTmpDir(): string {
  const dir = mkdtempSync(join(tmpdir(), 'squad-build-test-'));
  tmpDirs.push(dir);
  return dir;
}

/**
 * Create a minimal .squad/ directory with protected files pre-populated
 * so we can verify they're never overwritten.
 */
function scaffoldSquadDir(root: string): string {
  const squadDir = join(root, '.squad');
  mkdirSync(join(squadDir, 'agents', 'agent1'), { recursive: true });
  mkdirSync(join(squadDir, 'agents', 'agent2'), { recursive: true });
  mkdirSync(join(squadDir, 'orchestration-log'), { recursive: true });

  // Protected files — build must NOT touch these
  writeFileSync(join(squadDir, 'decisions.md'), '# Decisions\n\nManual decision log.\n');
  writeFileSync(join(squadDir, 'agents', 'agent1', 'history.md'), '# Agent1 History\n\nManual notes.\n');
  writeFileSync(join(squadDir, 'agents', 'agent2', 'history.md'), '# Agent2 History\n\nManual notes.\n');
  writeFileSync(
    join(squadDir, 'orchestration-log', '2026-03-01.md'),
    '# Session log\n\nManual entry.\n',
  );

  return squadDir;
}

/**
 * Build a minimal SquadSDKConfig for testing.
 */
function makeTestConfig(overrides?: Partial<SquadSDKConfig>): SquadSDKConfig {
  return {
    version: '1.0.0',
    team: {
      name: 'Test Squad',
      description: 'A test team',
      members: ['agent1', 'agent2'],
    },
    agents: [
      { name: 'agent1', role: 'TypeScript Engineer', charter: 'Writes clean TypeScript.' },
      { name: 'agent2', role: 'Tester', charter: 'Breaks things that can break.' },
    ],
    routing: {
      rules: [
        { pattern: 'feature-*', agents: ['agent1'] },
        { pattern: 'test-*', agents: ['agent2'] },
      ],
      defaultAgent: 'agent1',
    },
    ceremonies: [
      { name: 'standup', schedule: '0 9 * * 1-5', participants: ['agent1', 'agent2'] },
    ],
    ...overrides,
  };
}

// ============================================================================
// Local build stub — simulates `squad build` output generation.
//
// Build a minimal SquadSDKConfig for testing.
// When build command lands, replace local stubs with real imports.
// ============================================================================

interface BuildResult {
  filesWritten: string[];
  filesSkipped: string[];
}

interface CheckResult {
  exitCode: 0 | 1;
  driftFiles: string[];
}

function generateTeamMd(config: SquadSDKConfig): string {
  const lines: string[] = [GENERATED_HEADER, '', `# ${config.team.name}`];
  if (config.team.description) lines.push('', config.team.description);
  lines.push('', '## Members', '');
  for (const m of config.team.members) {
    const agent = config.agents.find((a) => a.name === m);
    lines.push(`- **${m}** — ${agent?.role ?? 'Unknown'}`);
  }
  return lines.join('\n') + '\n';
}

function generateRoutingMd(config: SquadSDKConfig): string {
  if (!config.routing) return '';
  const lines: string[] = [GENERATED_HEADER, '', '# Routing'];
  if (config.routing.defaultAgent) {
    lines.push('', `**Default agent:** ${config.routing.defaultAgent}`);
  }
  lines.push('', '## Rules', '');
  for (const rule of config.routing.rules) {
    lines.push(`- \`${rule.pattern}\` → ${rule.agents.join(', ')}`);
  }
  return lines.join('\n') + '\n';
}

function normalizeModelPref(
  model: BuilderModelId | ModelPreference | undefined,
): ModelPreference | undefined {
  if (!model) return undefined;
  if (typeof model === 'string') return { preferred: model };
  return model;
}

function generateCharterMd(agent: AgentDefinition, defaultModel?: BuilderModelId | ModelPreference): string {
  const lines: string[] = [
    GENERATED_HEADER,
    '',
    `# ${agent.name} — ${agent.role}`,
  ];
  if (agent.charter) lines.push('', agent.charter);
  const pref = normalizeModelPref(agent.model) ?? normalizeModelPref(defaultModel);
  if (pref) {
    lines.push('', '## Model', '');
    lines.push(`**Preferred:** ${pref.preferred}`);
    if (pref.rationale) lines.push(`**Rationale:** ${pref.rationale}`);
    if (pref.fallback) lines.push(`**Fallback:** ${pref.fallback}`);
  }
  if (agent.tools && agent.tools.length > 0) {
    lines.push('', '## Tools', '');
    for (const t of agent.tools) lines.push(`- ${t}`);
  }
  return lines.join('\n') + '\n';
}

function generateCeremoniesMd(config: SquadSDKConfig): string {
  if (!config.ceremonies || config.ceremonies.length === 0) return '';
  const lines: string[] = [GENERATED_HEADER, '', '# Ceremonies'];
  for (const c of config.ceremonies) {
    lines.push('', `## ${c.name}`);
    if (c.schedule) lines.push(`**Schedule:** ${c.schedule}`);
    if (c.participants && c.participants.length > 0) {
      lines.push(`**Participants:** ${c.participants.join(', ')}`);
    }
    if (c.agenda) lines.push('', c.agenda);
  }
  return lines.join('\n') + '\n';
}

/** Protected paths that `squad build` must NEVER write to. */
const PROTECTED_PATTERNS = ['decisions.md', 'history.md', 'orchestration-log'];

function isProtected(relativePath: string): boolean {
  return PROTECTED_PATTERNS.some((p) => relativePath.includes(p));
}

function runBuild(config: SquadSDKConfig, squadDir: string): BuildResult {
  const written: string[] = [];
  const skipped: string[] = [];

  // team.md
  const teamPath = join(squadDir, 'team.md');
  writeFileSync(teamPath, generateTeamMd(config));
  written.push('team.md');

  // routing.md
  if (config.routing) {
    const routingPath = join(squadDir, 'routing.md');
    writeFileSync(routingPath, generateRoutingMd(config));
    written.push('routing.md');
  }

  // agents/*/charter.md
  const defaultModel = config.defaults?.model;
  for (const agent of config.agents) {
    const charterDir = join(squadDir, 'agents', agent.name);
    mkdirSync(charterDir, { recursive: true });
    const charterPath = join(charterDir, 'charter.md');
    writeFileSync(charterPath, generateCharterMd(agent, defaultModel));
    written.push(`agents/${agent.name}/charter.md`);
  }

  // ceremonies.md
  if (config.ceremonies && config.ceremonies.length > 0) {
    const cerPath = join(squadDir, 'ceremonies.md');
    writeFileSync(cerPath, generateCeremoniesMd(config));
    written.push('ceremonies.md');
  }

  return { filesWritten: written, filesSkipped: skipped };
}

function checkBuild(config: SquadSDKConfig, squadDir: string): CheckResult {
  const driftFiles: string[] = [];

  const checks: Array<{ file: string; expected: string }> = [
    { file: 'team.md', expected: generateTeamMd(config) },
  ];

  if (config.routing) {
    checks.push({ file: 'routing.md', expected: generateRoutingMd(config) });
  }

  for (const agent of config.agents) {
    checks.push({
      file: `agents/${agent.name}/charter.md`,
      expected: generateCharterMd(agent, config.defaults?.model),
    });
  }

  if (config.ceremonies && config.ceremonies.length > 0) {
    checks.push({ file: 'ceremonies.md', expected: generateCeremoniesMd(config) });
  }

  for (const check of checks) {
    const fullPath = join(squadDir, ...check.file.split('/'));
    if (!existsSync(fullPath)) {
      driftFiles.push(check.file);
      continue;
    }
    const actual = readFileSync(fullPath, 'utf-8');
    if (actual !== check.expected) {
      driftFiles.push(check.file);
    }
  }

  return {
    exitCode: driftFiles.length === 0 ? 0 : 1,
    driftFiles,
  };
}

function dryRunBuild(config: SquadSDKConfig, squadDir: string): { diffs: string[]; filesWritten: number } {
  const diffs: string[] = [];

  const files: Array<{ file: string; expected: string }> = [
    { file: 'team.md', expected: generateTeamMd(config) },
  ];

  if (config.routing) {
    files.push({ file: 'routing.md', expected: generateRoutingMd(config) });
  }

  for (const agent of config.agents) {
    files.push({
      file: `agents/${agent.name}/charter.md`,
      expected: generateCharterMd(agent, config.defaults?.model),
    });
  }

  if (config.ceremonies && config.ceremonies.length > 0) {
    files.push({ file: 'ceremonies.md', expected: generateCeremoniesMd(config) });
  }

  for (const f of files) {
    const fullPath = join(squadDir, ...f.file.split('/'));
    if (!existsSync(fullPath)) {
      diffs.push(`+ ${f.file} (new file)`);
    } else {
      const actual = readFileSync(fullPath, 'utf-8');
      if (actual !== f.expected) {
        diffs.push(`~ ${f.file} (modified)`);
      }
    }
  }

  // Dry run — no files written
  return { diffs, filesWritten: 0 };
}

// ============================================================================
// Cleanup
// ============================================================================

afterEach(() => {
  for (const dir of tmpDirs) {
    try {
      rmSync(dir, { recursive: true, force: true });
    } catch {
      // best-effort cleanup
    }
  }
  tmpDirs.length = 0;
});

// ============================================================================
// Build generates team.md from config
// ============================================================================

describe('squad build — file generation', () => {
  it('generates team.md from config', () => {
    const root = makeTmpDir();
    const squadDir = scaffoldSquadDir(root);
    const config = makeTestConfig();

    runBuild(config, squadDir);

    const teamMd = readFileSync(join(squadDir, 'team.md'), 'utf-8');
    expect(teamMd).toContain('# Test Squad');
    expect(teamMd).toContain('A test team');
    expect(teamMd).toContain('**agent1**');
    expect(teamMd).toContain('**agent2**');
    expect(teamMd).toContain('TypeScript Engineer');
    expect(teamMd).toContain('Tester');
  });

  it('generates routing.md from config', () => {
    const root = makeTmpDir();
    const squadDir = scaffoldSquadDir(root);
    const config = makeTestConfig();

    runBuild(config, squadDir);

    const routingMd = readFileSync(join(squadDir, 'routing.md'), 'utf-8');
    expect(routingMd).toContain('# Routing');
    expect(routingMd).toContain('`feature-*`');
    expect(routingMd).toContain('agent1');
    expect(routingMd).toContain('`test-*`');
    expect(routingMd).toContain('agent2');
    expect(routingMd).toContain('**Default agent:** agent1');
  });

  it('generates agent charter files from config', () => {
    const root = makeTmpDir();
    const squadDir = scaffoldSquadDir(root);
    const config = makeTestConfig();

    runBuild(config, squadDir);

    const agent1Charter = readFileSync(join(squadDir, 'agents', 'agent1', 'charter.md'), 'utf-8');
    expect(agent1Charter).toContain('# agent1 — TypeScript Engineer');
    expect(agent1Charter).toContain('Writes clean TypeScript.');

    const agent2Charter = readFileSync(join(squadDir, 'agents', 'agent2', 'charter.md'), 'utf-8');
    expect(agent2Charter).toContain('# agent2 — Tester');
    expect(agent2Charter).toContain('Breaks things that can break.');
  });

  it('generates ceremonies.md from config', () => {
    const root = makeTmpDir();
    const squadDir = scaffoldSquadDir(root);
    const config = makeTestConfig();

    runBuild(config, squadDir);

    const ceremoniesMd = readFileSync(join(squadDir, 'ceremonies.md'), 'utf-8');
    expect(ceremoniesMd).toContain('# Ceremonies');
    expect(ceremoniesMd).toContain('## standup');
    expect(ceremoniesMd).toContain('0 9 * * 1-5');
    expect(ceremoniesMd).toContain('agent1, agent2');
  });
});

// ============================================================================
// Generated header
// ============================================================================

describe('squad build — generated header', () => {
  it('team.md includes the generated-by header', () => {
    const root = makeTmpDir();
    const squadDir = scaffoldSquadDir(root);
    runBuild(makeTestConfig(), squadDir);

    const content = readFileSync(join(squadDir, 'team.md'), 'utf-8');
    expect(content).toContain(GENERATED_HEADER);
    expect(content.indexOf(GENERATED_HEADER)).toBe(0);
  });

  it('routing.md includes the generated-by header', () => {
    const root = makeTmpDir();
    const squadDir = scaffoldSquadDir(root);
    runBuild(makeTestConfig(), squadDir);

    const content = readFileSync(join(squadDir, 'routing.md'), 'utf-8');
    expect(content).toContain(GENERATED_HEADER);
    expect(content.indexOf(GENERATED_HEADER)).toBe(0);
  });

  it('agent charter files include the generated-by header', () => {
    const root = makeTmpDir();
    const squadDir = scaffoldSquadDir(root);
    runBuild(makeTestConfig(), squadDir);

    for (const agentName of ['agent1', 'agent2']) {
      const content = readFileSync(join(squadDir, 'agents', agentName, 'charter.md'), 'utf-8');
      expect(content).toContain(GENERATED_HEADER);
      expect(content.indexOf(GENERATED_HEADER)).toBe(0);
    }
  });

  it('ceremonies.md includes the generated-by header', () => {
    const root = makeTmpDir();
    const squadDir = scaffoldSquadDir(root);
    runBuild(makeTestConfig(), squadDir);

    const content = readFileSync(join(squadDir, 'ceremonies.md'), 'utf-8');
    expect(content).toContain(GENERATED_HEADER);
    expect(content.indexOf(GENERATED_HEADER)).toBe(0);
  });
});

// ============================================================================
// Protected files — build must NEVER touch these
// ============================================================================

describe('squad build — protected files', () => {
  it('does NOT overwrite decisions.md', () => {
    const root = makeTmpDir();
    const squadDir = scaffoldSquadDir(root);
    const originalContent = readFileSync(join(squadDir, 'decisions.md'), 'utf-8');

    runBuild(makeTestConfig(), squadDir);

    const afterBuild = readFileSync(join(squadDir, 'decisions.md'), 'utf-8');
    expect(afterBuild).toBe(originalContent);
    expect(afterBuild).not.toContain(GENERATED_HEADER);
  });

  it('does NOT overwrite agent history.md files', () => {
    const root = makeTmpDir();
    const squadDir = scaffoldSquadDir(root);
    const agent1History = readFileSync(join(squadDir, 'agents', 'agent1', 'history.md'), 'utf-8');
    const agent2History = readFileSync(join(squadDir, 'agents', 'agent2', 'history.md'), 'utf-8');

    runBuild(makeTestConfig(), squadDir);

    expect(readFileSync(join(squadDir, 'agents', 'agent1', 'history.md'), 'utf-8')).toBe(agent1History);
    expect(readFileSync(join(squadDir, 'agents', 'agent2', 'history.md'), 'utf-8')).toBe(agent2History);
  });

  it('does NOT touch orchestration-log/ directory', () => {
    const root = makeTmpDir();
    const squadDir = scaffoldSquadDir(root);
    const logContent = readFileSync(
      join(squadDir, 'orchestration-log', '2026-03-01.md'),
      'utf-8',
    );

    runBuild(makeTestConfig(), squadDir);

    const afterBuild = readFileSync(
      join(squadDir, 'orchestration-log', '2026-03-01.md'),
      'utf-8',
    );
    expect(afterBuild).toBe(logContent);
  });

  it('protected file list: decisions.md, history.md, orchestration-log/', () => {
    // Verify the protection list is comprehensive
    expect(isProtected('decisions.md')).toBe(true);
    expect(isProtected('agents/agent1/history.md')).toBe(true);
    expect(isProtected('agents/agent2/history.md')).toBe(true);
    expect(isProtected('orchestration-log/2026-03-01.md')).toBe(true);

    // Generated files should NOT be protected
    expect(isProtected('team.md')).toBe(false);
    expect(isProtected('routing.md')).toBe(false);
    expect(isProtected('agents/agent1/charter.md')).toBe(false);
    expect(isProtected('ceremonies.md')).toBe(false);
  });
});

// ============================================================================
// --check mode
// ============================================================================

describe('squad build --check', () => {
  it('returns exit code 0 when generated files match disk', () => {
    const root = makeTmpDir();
    const squadDir = scaffoldSquadDir(root);
    const config = makeTestConfig();

    // First, build the files
    runBuild(config, squadDir);

    // Then, check — should match
    const result = checkBuild(config, squadDir);
    expect(result.exitCode).toBe(0);
    expect(result.driftFiles).toHaveLength(0);
  });

  it('returns exit code 1 when files differ (drift detected)', () => {
    const root = makeTmpDir();
    const squadDir = scaffoldSquadDir(root);
    const config = makeTestConfig();

    // Build with initial config
    runBuild(config, squadDir);

    // Manually edit team.md to simulate drift
    writeFileSync(join(squadDir, 'team.md'), '# Manually Edited\n\nSomebody changed this.\n');

    const result = checkBuild(config, squadDir);
    expect(result.exitCode).toBe(1);
    expect(result.driftFiles).toContain('team.md');
  });

  it('returns exit code 1 when generated file is missing', () => {
    const root = makeTmpDir();
    const squadDir = scaffoldSquadDir(root);
    const config = makeTestConfig();

    // Don't build — files missing
    const result = checkBuild(config, squadDir);
    expect(result.exitCode).toBe(1);
    expect(result.driftFiles.length).toBeGreaterThan(0);
    expect(result.driftFiles).toContain('team.md');
  });

  it('detects drift in charter files', () => {
    const root = makeTmpDir();
    const squadDir = scaffoldSquadDir(root);
    const config = makeTestConfig();

    runBuild(config, squadDir);

    // Tamper with one charter
    writeFileSync(
      join(squadDir, 'agents', 'agent1', 'charter.md'),
      '# Agent1 — Hacked Role\n\nSomeone changed this charter.\n',
    );

    const result = checkBuild(config, squadDir);
    expect(result.exitCode).toBe(1);
    expect(result.driftFiles).toContain('agents/agent1/charter.md');
    // Other files should not be flagged
    expect(result.driftFiles).not.toContain('agents/agent2/charter.md');
  });
});

// ============================================================================
// --dry-run mode
// ============================================================================

describe('squad build --dry-run', () => {
  it('does not write any files', () => {
    const root = makeTmpDir();
    const squadDir = scaffoldSquadDir(root);
    const config = makeTestConfig();

    const result = dryRunBuild(config, squadDir);

    // Verify no generated files exist
    expect(existsSync(join(squadDir, 'team.md'))).toBe(false);
    expect(existsSync(join(squadDir, 'routing.md'))).toBe(false);
    expect(existsSync(join(squadDir, 'ceremonies.md'))).toBe(false);
    expect(result.filesWritten).toBe(0);
  });

  it('reports which files would be created', () => {
    const root = makeTmpDir();
    const squadDir = scaffoldSquadDir(root);
    const config = makeTestConfig();

    const result = dryRunBuild(config, squadDir);

    expect(result.diffs.length).toBeGreaterThan(0);
    expect(result.diffs.some((d) => d.includes('team.md'))).toBe(true);
    expect(result.diffs.some((d) => d.includes('routing.md'))).toBe(true);
  });

  it('reports which files would be modified', () => {
    const root = makeTmpDir();
    const squadDir = scaffoldSquadDir(root);
    const config = makeTestConfig();

    // Build first so files exist
    runBuild(config, squadDir);

    // Tamper with one file
    writeFileSync(join(squadDir, 'team.md'), '# Old Content\n');

    const result = dryRunBuild(config, squadDir);
    expect(result.diffs.some((d) => d.includes('team.md') && d.includes('modified'))).toBe(true);
    expect(result.filesWritten).toBe(0);

    // Verify file was NOT overwritten
    const content = readFileSync(join(squadDir, 'team.md'), 'utf-8');
    expect(content).toBe('# Old Content\n');
  });

  it('reports nothing when all files match', () => {
    const root = makeTmpDir();
    const squadDir = scaffoldSquadDir(root);
    const config = makeTestConfig();

    // Build so files match
    runBuild(config, squadDir);

    const result = dryRunBuild(config, squadDir);
    expect(result.diffs).toHaveLength(0);
  });
});

// ============================================================================
// Edge cases
// ============================================================================

describe('squad build — edge cases', () => {
  it('creates agent directories that do not yet exist', () => {
    const root = makeTmpDir();
    const squadDir = join(root, '.squad');
    mkdirSync(squadDir, { recursive: true });

    const config = makeTestConfig({
      agents: [
        { name: 'new-agent', role: 'Newcomer', charter: 'Fresh off the boat.' },
      ],
      team: { name: 'Solo', members: ['new-agent'] },
    });

    runBuild(config, squadDir);

    expect(existsSync(join(squadDir, 'agents', 'new-agent', 'charter.md'))).toBe(true);
    const charter = readFileSync(join(squadDir, 'agents', 'new-agent', 'charter.md'), 'utf-8');
    expect(charter).toContain('new-agent');
    expect(charter).toContain(GENERATED_HEADER);
  });

  it('handles config with no routing (skips routing.md)', () => {
    const root = makeTmpDir();
    const squadDir = join(root, '.squad');
    mkdirSync(squadDir, { recursive: true });

    const config = makeTestConfig({ routing: undefined });

    runBuild(config, squadDir);

    expect(existsSync(join(squadDir, 'team.md'))).toBe(true);
    expect(existsSync(join(squadDir, 'routing.md'))).toBe(false);
  });

  it('handles config with no ceremonies (skips ceremonies.md)', () => {
    const root = makeTmpDir();
    const squadDir = join(root, '.squad');
    mkdirSync(squadDir, { recursive: true });

    const config = makeTestConfig({ ceremonies: undefined });

    runBuild(config, squadDir);

    expect(existsSync(join(squadDir, 'team.md'))).toBe(true);
    expect(existsSync(join(squadDir, 'ceremonies.md'))).toBe(false);
  });

  it('build result reports all written files', () => {
    const root = makeTmpDir();
    const squadDir = scaffoldSquadDir(root);
    const config = makeTestConfig();

    const result = runBuild(config, squadDir);

    expect(result.filesWritten).toContain('team.md');
    expect(result.filesWritten).toContain('routing.md');
    expect(result.filesWritten).toContain('agents/agent1/charter.md');
    expect(result.filesWritten).toContain('agents/agent2/charter.md');
    expect(result.filesWritten).toContain('ceremonies.md');
    expect(result.filesWritten).toHaveLength(5);
  });
});
